### PR TITLE
Ipdc improvements

### PR DESCRIPTION
**Pull request by Brow71189**

### CODE REVIEW

**Comment by cmeyer** [comment]
Can you squash or rebase these and force push? 19 commits for a relatively small change is a lot of noise in the commit log. Is there any reason for the history of merges in this PR?

**Comment by Brow71189** [comment]
> Can you squash or rebase these and force push? 19 commits for a relatively small change is a lot of noise in the commit log. Is there any reason for the history of merges in this PR?

Honestly I have no idea why I get these massive history diffs here. The actual changes I want are in the last two commits. Shouldn't "Squash and merge" just fix this, i.e. create one commit for all the changes.

**Comment by Brow71189** [comment]
Actually, this also contains the Wizard changes...Somehow my local copy of this repo is in a weird state.

I'll rebase, keep only the relevant commits and just make a new PR.

**Comment by cmeyer** [comment]
Also, in the interest of improving communication, can you explain the purpose of this change? Ideally file an issue and link the PR to the issue. I'd like to have enough info so that we know why the change was made, how QA can test it, how users can use it. It might be overkill for this issue, but we should start that process for better communication/visibility. At the very minimum, we should include an entry in CHANGES since this seems to affect end users.

Cc @Ion-e

**Comment by cmeyer** [comment]
> Actually, this also contains the Wizard changes...Somehow my local copy of this repo is in a weird state.
> 
> I'll rebase, keep only the relevant commits and just make a new PR.

Does it require the new wizard code, which is still in #32?

**Comment by Brow71189** [comment]
> > Actually, this also contains the Wizard changes...Somehow my local copy of this repo is in a weird state.
> > I'll rebase, keep only the relevant commits and just make a new PR.
> 
> Does it require the new wizard code, which is still in #32?

It also adds the new Wizard code, so #31 would be obsolete. As I said, my local copy of this repo is a bit in a weird state.

I agree with the communication issues you raised. Maybe I will just add a CHANGES entry here though, because these are very minimal changes that just add some parameters to a computation.

Going forward I'll start with a proper process. Is that ok?

**Comment by cmeyer** [comment]
> It also adds the new Wizard code, so https://github.com/nion-software/experimental/pull/31 would be obsolete. As I said, my local copy of this repo is a bit in a weird state.

Ideally the Wizard and the Ipdc improvements could be separate PR's since they are not related at all. Again, I'm not too picky about this in this particular project, but it's a good practice going forward.

**Comment by Brow71189** [comment]
Ok so these are the 3 relevant commits now. I think we should "Rebase and merge" them into master, because it doesn't make sense to squash them since they add very different functionality.

**Comment by cmeyer** [comment]
@Brow71189 Please merge!

**Comment by cmeyer** [comment]
Note: I'm fine with copying the metadata for now in this one case, but for reference:
- https://github.com/nion-software/nionswift/issues/915

**Pull request merged**
